docs: Adding 'Troubleshooting' to the 'Migrating to devfile v2' docs
devfile/docs pull request #153
Opened 2022-04-27 12:37 UTC by ibuziuk

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
Related issue - https://github.com/eclipse/che/issues/21005

2022-04-28 17:36 UTC, l0rd reviewed
The content is good but we are talking about DevWorkspaces, editors, conversion and an `odo` user may get lost. I think we should set the context: that's about v1 Devfiles written for Eclispe Che or CodeReady Workspaces that got translated into v2 Devfiles (manually[add the link to the guide] or automatically[add the link to the npm lib]). The error that are troubleshooted here are Eclipse Che or OpenShift Dev Spaces (DevWorkspace) workpace startup errors (not odo, OpenShift Console). In the future, we may add a troubleshooting `odo` errors (when testing a migrated devfile) section here.

2022-04-29 08:39 UTC, ibuziuk commented
@l0rd thanks for review, I have set a clear context for the troubleshooting section

![image](https://user-images.githubusercontent.com/1461122/165911411-c4191cea-ec5c-474a-a0a8-575a36c1c7d5.png)

Other tools could contribute to this doc by adding another tool specific section e.g. `odo` errors after the devfile v2 migration

2022-04-29 08:55 UTC, l0rd approved these changes
LGTM

2022-04-29 09:31 UTC, ibuziuk commented
@rkratky could you please review
my understanding is that once merged the docs team will cherry-pick it to relevant branches.

2022-04-29 13:15 UTC, rkratky requested changes
@ibuziuk, thanks. Some suggestions added.

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +[id="proc_trobleshooting_{context}"]
```suggestion
[id="troubleshooting_{context}"]
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> += Trobleshooting
```suggestion
= Troubleshooting
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +====
```suggestion
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +====
```suggestion
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +- If a workspace fails to start after the conversion try referencing the link:https://quay.io/repository/devfile/universal-developer-image[Universal Developer Image] as the only component in the devf
```suggestion
Workspace fails to start after the conversion:: Try referencing the link:https://quay.io/repository/devfile/universal-developer-image[Universal Developer Image] as the only component in the devfile:
+
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +
```suggestion
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +
```suggestion
+
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +- If the conversion fails with the `Error processing devfile: failed to merge DevWorkspace volumes: duplicate volume found in devfile: volume_name` this means that there are multiple volumes defined
```suggestion
.Conversion failures

Conversion fails with `Error processing devfile: failed to merge DevWorkspace volumes: duplicate volume found in devfile: volume_name`:: This means there are multiple volumes defined in the original devfile with the same name. Remove the duplicate volumes and proceed with the conversion.
```

2022-04-29 13:15 UTC, rkratky commented on docs/modules/user-guide/partials/proc_troubleshooting.adoc
> +- If the conversion fails with the `Error provisioning storage: Could not rewrite container volume mounts: volume component 'volume_name' is defined multiple times` this means that the volume defined
```suggestion
Conversion fails with `Error provisioning storage: Could not rewrite container volume mounts: volume component 'volume_name' is defined multiple times`:: This means the volume defined in the original devfile conflicts with a `volumeMount` propagated by an editor or a plug-in. Rename the volume in the defvile to be the same as the name of the `volumeMount` it conflicts with, and proceed with the conversion.
```

2022-04-29 13:58 UTC, ibuziuk commented
@rkratky thanks, the suggestions have been applied

2022-05-04 14:11 UTC, rkratky approved these changes

2022-05-04 14:11 UTC, merged