[WIP]: Updated specs
devfile/docs pull request #21
Opened 2020-11-13 18:46 UTC by jc-berger

For issue [#158](https://github.com/devfile/api/issues/158)

2020-11-16 22:33 UTC, elsony requested changes

2020-11-16 22:33 UTC, elsony commented on docs/modules/ROOT/partials/proc_writing-a-devfile-for-your-project.adoc
>  components:
It should be changed to:
```
components:
  - name: javaPlugin
    plugin:
      id: redhat/java/latest
```

2020-11-17 19:32 UTC, jc-berger commented on docs/modules/ROOT/partials/proc_writing-a-devfile-for-your-project.adoc
>  components:
addressed, so resolved conversation

2020-11-17 19:42 UTC, jc-berger commented
@elsony, thanks, luckily that was a quick fix! Revised commit is up, thanks.

2020-11-18 19:03 UTC, elsony approved these changes
/lgtm

2020-11-19 16:07 UTC, merged