Update migration guide.
devfile/docs pull request #22
Opened 2020-11-18 10:55 UTC by boczkowska

Added description of v2 changes w/ links to respective issues and some language suggestions. 

Docs issue: https://github.com/devfile/api/issues/160

2020-11-18 10:57 UTC, boczkowska commented
@elsony could you PTAL if everything is correct content-wise?
@jc-berger could you please provide a language review? :relaxed: 

Thanks.

2020-11-18 23:35 UTC, elsony requested changes

2020-11-18 23:35 UTC, elsony commented on docs/modules/ROOT/pages/migration_guide.adoc
>  Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/31[corresponding issue].
Change URL prefix, see above.

2020-11-18 23:35 UTC, elsony commented on docs/modules/ROOT/pages/migration_guide.adoc
>  Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/21[corresponding issue].
Change URL prefix, see above.

2020-11-18 23:35 UTC, elsony commented on docs/modules/ROOT/pages/migration_guide.adoc
>  Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/22[corresponding issue].
Change URL prefix, see above.

2020-11-18 23:35 UTC, elsony commented on docs/modules/ROOT/pages/migration_guide.adoc
>  Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/18[corresponding issue].
Change URL prefix, see above.

2020-11-18 23:35 UTC, elsony commented on docs/modules/ROOT/pages/migration_guide.adoc
> +  - id: helloWorld
This should be `name` instead of `id`

2020-11-23 12:47 UTC, boczkowska commented on docs/modules/ROOT/pages/migration_guide.adoc
> +=== `starterProjects` and projects description
Good catch! Added backticks around `project.`

2020-11-23 12:48 UTC, boczkowska commented on docs/modules/ROOT/pages/migration_guide.adoc
> +A component specified in a v1.0 devfile will not work as it is in a devfile v2.0.
I've readded the sentence. Probably removed it by accident the first time.

2020-11-23 12:48 UTC, boczkowska commented
@elsony Thank you for the review! I've changed the URLs and addressed your other feedback. PTAL when you have time.

2020-11-23 15:55 UTC, elsony approved these changes
lgtm

2020-11-23 16:59 UTC, rkratky requested changes
@boczkowska, adding a bunch of nitpicks.

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +== Migrating plugins
```suggestion
== Migrating plug-ins
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
>  There ARE major changes about the definition of plugins in a devfile. Plugins are now specified using a devfile. A plugin specified in a v1.0 meta.yaml will NOT work as it is in a devfile v2.0.
```suggestion
Plug-ins are specified using a devfile. A plug-in specified in a v1.0 `meta.yaml` does not work as is in a devfile v2.0.
```
Do not use CAPS in docs.

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +Details can be found in the https://github.com/devfile/api/issues/4[corresponding issue].
All of the _"Details can be found in the >corresponding issue<."_ sentences would look better with:

* No passive tense
* Title of the linked issue

E.g.: _"For more details, see >Polymorphic component type UX in a devfile<."_

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +=== Replace alias with Name
```suggestion
=== Replace alias with name
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
>  For a better syntax validation component now is defined as a polymorphic type and can be implemented as `container`, `kubernetes`, `openshift`, `plugin` or `volume`.
```suggestion
For better syntax validation, a component now is defined as a polymorphic type and can be implemented as `container`, `kubernetes`, `openshift`, `plugin`, or `volume`.
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +In v2 of the devfile we have added some new metadata like `version` (this is the https://github.com/devfile/api/issues/10[corresponding issue]) and some mandatory metadata for plugins (this is the ht
```suggestion
Version 2 of the devfile adds new metadata, including `version` (see link:https://github.com/devfile/api/issues/10[The devfile schema/samples should have version and name]) and some mandatory metadata for plug-ins (see link:https://github.com/devfile/api/issues/31[Better plugin mechanism]).
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +<1> Mandatory if there is more than one remote
```suggestion
<1> Mandatory if there is more than one remote.
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +<2> The revision that should be used checked out. May be a branch name, tag or commit id. Default branch should be checked out if missing.
```suggestion
<2> The revision that should be used checked out. May be a branch name, tag, or commit id. Default branch should be checked out if missing.
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +<3> The remote name should be used as init. Required if there are more than one remote configured.
```suggestion
<3> The remote name that should be used as init. Required if there are more than one remote configured.
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +`mountSources` field is defined as `true` for all non-plugin components and components that do not set dedicatedPod to `true`.
```suggestion

The `mountSources` field is defined as `true` for all non-plug-in components and components that do not set `dedicatedPod` to `true`.
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +`hotReloadCapable` defines whether the command is capable to reload itself when source code changes. If set to `true` the command will not be restarted and it is expected to handle file changes on it
```suggestion

The `hotReloadCapable` fields defines whether the command is capable of reloading itself when source code changes. If set to `true`, the command is not restarted, and it is expected to handle file changes on its own. 
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> += Migrating from devfile v1 to devfile v2
Unless there's a specific reason not to, I believe the use of `v1` vs `v1.0` and `v2` vs `v2.0` should be unified.

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
>  Attribute `apiVersion` has been renamed `schemaVersion`:
```suggestion
Attribute `apiVersion` has been renamed to `schemaVersion`:
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +A project specified in a v1.0 devfile works as it is in a devfile v2.0. The only major change is the addition of a new kind of project: `starterProjects`. Those are supposed to be used in interactive
```suggestion
A project specified in a v1.0 devfile works as is in a devfile v2.0. The only major change is the addition of a new kind of project: `starterProjects`. Those are supposed to be used in interactive mode only (user must pick one) and the Git repository cannot be cloned. Instead, only source code is to be copied (for example, `git archive --remote=_<repository URL>_ | tar -t`).
```

2020-11-23 16:59 UTC, rkratky commented on docs/modules/ROOT/pages/migration_guide.adoc
> +There are major changes in the `components` section of the devfile. A component specified in a v1.0 devfile will not work as it is in a devfile v2.0.
```suggestion

There are major changes in the `components` section of the devfile. A component specified in a v1.0 devfile does not work as is in a devfile v2.0.
```

2020-11-24 15:14 UTC, boczkowska commented
@rkratky thanks! PTAL

2020-11-26 15:34 UTC, rkratky approved these changes
Thanks, @boczkowska.

2020-11-26 15:34 UTC, merged