WIP: added links
devfile/docs pull request #30
Opened 2020-12-11 20:42 UTC by jc-berger

For issue [#180](https://github.com/devfile/api/issues/180)

I've added links under our `Devfile Samples` page so users can access the docs repo as well. I thought a name change to `Devfile resources` would make it more intuitive to the users. If we like the name change idea, I'll have to change the name of the actual doc and in the TOC. 

I'm trying to give more context as to why users would even want to visit our repos. If anyone has suggestions for more context, that'd be appreciated. 

Also, to my knowledge, there's no communication channel to link users to, like a YouTube channel, blog page, Twitter account, etc. But those can be considerations, moving forward!

2020-12-11 20:53 UTC, elsony requested changes

2020-12-11 20:53 UTC, elsony commented on docs/modules/user-guide/partials/ref_devfile-samples.adoc
> +* To view devfile issues and open issues, go to https://github.com/devfile/api/tree/master/samples/devfiles[Devfile Samples]
We probably should have 2 different entries:
1. Should the issue link be: https://github.com/devfile/api/issues?
2. add a different description for the sample link.

2020-12-15 16:21 UTC, jc-berger commented
Thanks, @elsony, new, squashed commit is up.

2020-12-18 20:08 UTC, elsony approved these changes
LGTM

2021-01-06 18:47 UTC, jc-berger commented
@rkratky, this PR is ready to merge if it also looks good after your review. Thanks you, and thanks, Elson, for the SME review!

2021-01-07 19:11 UTC, jc-berger commented
Note: working with Eva to complete doc peer review.

2021-01-12 09:05 UTC, Eva-Lotte commented
LGTM!

2021-01-21 16:05 UTC, merged